name: 'PR Close - Dev'
on:
  pull_request:
    branches:
      - develop
    types:
      - closed
jobs:
  merge_pr:
    name: 'PR Merged'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ORG_PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Git config
        run: |
          git config --global user.email "${{ secrets.GH_ORG_EMAIL }}"
          git config --global user.name "${{ secrets.GH_ORG_NAME }}"
      - name: Apply version bump (major)
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: |
          cd packages/ebon
          npm version major
          git add package.json
          git commit -m "Bump version to $(node -p "require('./package.json').version")"
      - name: Apply version bump (minor)
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: |
          cd packages/ebon
          npm version minor
          git add package.json
          git commit -m "Bump version to $(node -p "require('./package.json').version")"
      - name: Apply version bump (patch)
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: |
          cd packages/ebon
          npm version patch
          git add package.json
          git commit -m "Bump version to $(node -p "require('./package.json').version")"
      - name: Git push version bump
        run: git push origin develop --follow-tags --force
      - id: get-version
        name: Output version change
        run: |
          cd packages/ebon
          npm pkg get version
