name: 'Main - PR Close'
on:
  pull_request:
    branches:
      - main
    types:
      - closed
jobs:
  merge_pr_main:
    name: 'PR Merged (main) - Create Release'
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release npm')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ORG_PAT }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
      - id: get-version
        name: Output package/core version
        run: |
          cd /packages/core
          npm pkg get version
      # if "release npm" label is present, create a release with tag equal to the version and the PR title as the release title
      - name: Create release
        if: contains(github.event.pull_request.labels.*.name, 'release npm')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ORG_PAT }}
        with:
          tag_name: ${{ steps.get-version.outputs.stdout }}
          release_name: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
