name: Publish to NPM
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Setup Yarn
        uses: mskelton/setup-yarn@v1
        with:
          node-version: '20.x'
      - name: Install dependencies and build 🔧
        run: |
          cd packages/core
          yarn ci && yarn build
      - name: Publish package on NPM 📦
        run: |
          cd packages/core
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
